phpcs.xml
This update fixes the indentation rule in switch statements.
=> Update the phpcs.xml indentation rule

_config.yml
Added Scheduled jobs section to navigation.
=> Added Scheduled jobs section

composer.json
also removed unused elasticpress plugin
=> added enhanced medialibrary + stream plugins

README.md
Add the snippet of text to the bottom of the readme
=> Add descriptions of used plugins to readme

docker-compose.yml
sync related keywords changed to PROJECTNAME because they need to be replaced another way than THEMENAME
=> change sync related keywords

docker-sync.yml
THEMENAME -> PROJECTNAME change to docker-sync.yml also
=> PROJECTNAME keyword to docker-sync.yml

CHANGELOG.md, Dockerfile, nginx/server/security.conf
Mahdollisuus verifioida sertifikaatti URLilla.
https://geniemdev.atlassian.net/browse/WPTEAM-82
=> SSL-verification

nginx/server/security.conf
Disabled /author to block author username fishing
=> blocked author in nginx security.conf file

CHANGELOG.md, nginx/http/cors-map.conf, nginx/server/cors-headers.conf, nginx/server/proxy-settings.conf
removed browser cache cause it causes havoc in admin
=> Remove browser cache

CHANGELOG.md, nginx/http/cors-map.conf, nginx/server/cors-headers.conf
added cors headers for use with multisite. lines are commented.
=> added cors headers for multisite

config/application.php
Change stateless cache busting constant to the new version
=> Stateless constant change

tasks.cron
Changed the path to match the proper cron script path. Is this right @Hooace ?
=> Change path of cron script

.csscomb.json, .gitignore, .sass-lint.yml, CHANGELOG.md, composer.json, config/application.php, docker-compose-ubuntu.yml, tasks.cron, web/app/db.php, web/db-config.php
- Change cron url from `tasks.cron` to match the correct path in `scripts`.
- Add `web/core`to gitignore.
- Add lines to sass-lint.
- Change color shorthand rule from csscomb.json.
- Change proper IP addresses to `docker-compose-ubuntu.yml`.
- Change SEO collection version to ^2.0 in `composer.json`.
- Add phpcs ignores to `db-config.php` and `db.php`.
- Fix code style errors from `application.php`.
=> minor fixes to project boilerplate. more info in the changelog.

CHANGELOG.md, kontena-production.yml, kontena-stage.yml
to prevent container to comsume all memory it is now limited to 2Gb
=> memorylimit added

CHANGELOG.md, docker-compose-gcloud.yml, docker-compose-ubuntu.yml, docker-compose.yml
- Correct error log path variables for PHP and NGINX for local environments and the Google Cloud build.
=> Error log paths

CHANGELOG.md, scripts/run-cron.sh
- Allow insecure connection when using curl for the cron url.
- Change file permissions to allow execution for the run-cron.sh.
=> Cron fixes

config/application.php
lisätty oikea nginx helper path configiin
=> nginxhelper path

.eslintrc.json, CHANGELOG.md, composer.json, package-lock.json, package.json
Added package.json with husky and linters and updated eslint config.
=> Feature: Linting

CHANGELOG.md, composer.json, composer.lock
Also removed duplicate scripts section, added roave/security-advisories.
=> Package updates, ready for Composer v2

composer.json, composer.lock, config/application.php
From devgeniem/redis-cache (private internal) to [wpackagist-plugin/redis-cache](https://wordpress.org/plugins/redis-cache/)
=> Redis cache plugin switch
