phpcs.xml
Removed *.dust and *.twig exclude rules from phpcs.xml. These prevent linting files in directories with a name containing "twig" or "dust".
=> Update exclude rules in phpcs.xml

composer.json
Remove the dependency, because it is a meta package that requires two dependencies that are already required in the project composer.json and in the wp-safe-fast-and-clean-collection -meta package.
=> Remove wp-security-collection from composer.json

CHANGELOG.md, config/application.php
The WordPress option `blog_public` is now controlled with a read only option defined in `application.php`.
=> Search engine visibility is controlled with an env

config/application.php
Remove PLL_LINGOTEK_AD, causes problems with pro version of polylang.
Solves #52, after [this](https://github.com/devgeniem/wp-safe-fast-and-clean-collection/pull/3) PR is merged.
=> Remove PLL_LINGOTEK_AD

CHANGELOG.md, config/application.php
- Change the default revision amount to 5.
- Use `filter_var` on accessing server variables instead of `filter_input` to support PHP7.x.
=> Fix application configurations

nginx/server/proxy-settings.conf
Comment the expires 5m line out so that the cache is not set. This fixes admin caching problems.
=> Disable 5min http request cache

CHANGELOG.md, docker-compose-ubuntu.yml, docker-compose.yml
- Xdebug profiling data is stored in a global volume and not synced to the local machine.
=> Add a global xdebug volume for xdebug profiling data

CHANGELOG.md, config/environments/development.php, config/environments/production.php, config/environments/staging.php
- `WP_REDIS_MAXTTL` constant set to 30 days for production environment and to 4 hours for staging environment.
- `WP_REDIS_MAXTTL` constant set to 60 seconds for development environment.
=> Set max ttl for object cache

CHANGELOG.md, scripts/run-cron.sh
- Changed run-cron.sh to use basic authentication if envs BASIC_AUTH_USER and BASIC_AUTH_PASSWORD has been setted.
=> Run cron basic authentication

Dockerfile
This fixes following warning during `docker build`:
```
[WARNING]: Empty continuation line found in:
RUN addgroup --system --gid $WEB_GID $WEB_GROUP &&     adduser --system --gid $WEB_GID --uid $WEB_UID $WEB_USER &&     dpkg-reconfigure tzdata
[WARNING]: Empty continuation lines will become errors in a future release.
```
=> Fix empty continuation line found warning

CHANGELOG.md, nginx/server/security.conf
- Make the deny rule for author urls to be more exact to prevent mismatching locations.
=> Fix the author url deny rule

CHANGELOG.md, composer.json
Add `devgeniem/wp-disable-redis-object-cache-dropin` to disable Redis object caching on WP preview.
=> Add devgeniem/wp-disable-redis-object-cache-dropin

phpcs.xml
Either this or:
```
<rule ref="Generic.Arrays.DisallowShortArraySyntax">
```
should be added to the php linting rules to make the code more consistent, in this case i added the rule to disallow the long syntax but this is purely a personal preference and can be switched to the other one.
=> disallow long array syntax

CHANGELOG.md, gcloud/cloudbuild_production.yaml, gcloud/cloudbuild_stage.yaml
**CHANGED**
- Cloud build fixes where `npm run build` is run instead of `./node_modules/webpack/bin/webpack.js`
=> Cloud build yaml fixes when running webpack

CHANGELOG.md, README.md
- Took line width below 120, where possible.
- Removed references (that I found) to things we are no longer supporting, such as travis-ci build status, Drone CI and phantomjs testing
- Rewrote urls as [shortcut reference links](https://github.github.com/gfm/#shortcut-reference-link)
- Improved workflow documentation.
- Improved composer repository and used plugins / vendor packages listing with the magic of tables
=> README Improvements

.editorconfig, .eslintignore, .sass-lint.yml, CHANGELOG.md
- Added `.eslintignore`
- Modified `.editorconfig` with dust and yaml specific changes
- Modified `.sass-lint.yml`
- to allow [placeholder-in-extend](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/placeholder-in-extend.md)
- to include all `web/app/themes` asset folders
- to ignore `node_modules` under `web/app/themes` and everything under `web/wp`
=> sass-lint and eslint configurations, some fixes

CHANGELOG.md, composer.json, composer.lock
Added [devgeniem/wp-geniem-project-bells-and-whistles](https://github.com/devgeniem/wp-geniem-project-bells-and-whistles) (mu-plugin)
> This WordPress mu-plugin is a collection of fixes and configurations for Geniem WordPress projects. A mu-plugin ensures that all functionalities get executed at an early stage of the WordPress bootstrap process and execution order can be controlled by using WordPress actions and filters.
Current available fixes:
- DisableAdminEmailVerification: Disable WordPress periodical admin email verification
- FixStreamDateFormat: Fix a date format bug in WP Stream database queries.
- Add404Headers: Remove no-cache headers from 404 error pages.
- CheckTasksCronFile: Verify there's a newline at the end of tasks.cron file.
=> Added wp-geniem-project-bells-and-whistles

CHANGELOG.md, config/application.php
- Changed `WP_STATELESS_MEDIA_MODE` to `cdn`. This helps to prevent sync, upload and performance problems with wp-stateless.
=> wp-stateless media mode to cdn

CHANGELOG.md, README.md, docker-compose.yml
Update Docker Composer configurations to work with the base image's new version using Xdebug 3.
=> Migrate to Xdebug 3

composer.json, composer.lock, phpcs.xml
- Added PHP 8 as a supported PHP version.
- Changed WordPress minimum version from 5.5.1 to 5.7.
- Removed `devgeniem/wp-cron-runner` from special git repositories.
- Upgraded johnpbloch/wordpress (5.5.1 => 5.7.0)
- Upgraded johnpbloch/wordpress-core (5.5.1 => 5.7.0)
- Upgraded koodimonni-language/core-fi (5.5.1 => 5.7)
- Upgraded devgeniem/acf-codifier (1.35.1 => 1.36.0)
- Upgraded devgeniem/dustpress (1.30.0 => 1.33.0.1)
- Upgraded devgeniem/dustpress-debugger (1.5.4 => 1.7.0)
- Upgraded devgeniem/wp-cron-runner (1.0.3  => 1.0.3 52c04ba)
- Upgraded devgeniem/wp-geniem-project-bells-and-whistles (1.4.0 => 1.5.0)
- Upgraded devgeniem/wp-stateless-bucket-link-filter (1.0.1 => 1.1.0)
- Upgraded rarst/wps dependencies -- **with dependencies**
- Upgraded vlucas/phpdotenv (v2.6.6 => v2.6.7)
- …
=> Updated composer packages
